### ISSUE TITLE
Deploying to gh-pages issue

### ISSUE THREAD

**Issue by cluzier** [rajatkulkarni95/rk-minimal#22]
When deploying to gh-pages I am running into an issue where it cannot find the build folder.

```
deploy
> gh-pages -d build

ENOENT: no such file or directory, stat '/Users/username/Desktop/username.github.io/build'
```

my package.json scripts are as follows:
```
"scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint",
        "migrate:dev": "npx prisma migrate dev",
        "generate": "ts-node --transpile-only src/graphql/schema",
        "predeploy": "npm run build",
        "deploy": "gh-pages -d build"
    },
```

Do I need to change the path for build? I have never run into this issue before, any help is appreciated. Thanks 👍

**Comment by rajatkulkarni95** [comment]
@cluzier AFAIK, github pages only allow for static html deployments and since the app requires a node server, won't work with github pages.

Try deploying to either of `netlify` or `vercel` or any of the other node compatible deployment servers
